name: Check URLs
on: workflow_dispatch
jobs:
  check_urls:
    name: Check URLs are valid
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: List files
        run: ls -al

#      - name: Hello world action step
#        id: hello
#        uses: ./.github/actions/check-urls
#        with:
#          who-to-greet: Geoff
#
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
