name: Hello World
on: workflow_dispatch
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
#        with:
#          sparse-checkout: |
#            README.md
#          sparse-checkout-cone-mode: false

      - name: Say Hello
        run: echo "Hello, World!"

      - name: List files
        run: ls -al
