name: Check URLs
on: workflow_dispatch
jobs:
  sparse_checkout:
    name: Sparse checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            build.gradle.kts
          sparse-checkout-cone-mode: false

      - name: List files
        run: ls -al
